var dumyData = [
  {
    marque: 'GG matelassé tote',
    description:
      'Matelassé leather is a signature material of the House, thanks to its super soft finish. The textured GG motif defines a selection of handbags, including this brown leather tote bag. The Double G hardware decorates the front, continuing the logo feel of the design.',
    image: 'img1.png',
  },

  {
    marque: 'WOMEN S BALENCIAGA  ADIDAS TRIPLE S TRAINERS IN WHITE',
    description:
      'adidas Triple S Trainers in white  black and grey double foam and mesh are done in collaboration with adidas',
    image: 'img2.png',
  },
];

module.exports = dumyData;
