import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import NavBar from './Navbar component/NavBar'
import ProSlides from './ProSlides'
import SlidesWomen from './SlidesWomen'
import Login from './Login'
import Link from 'next/link'
// import { useNavigate } from "react-router-dom";


export default function Home() {
  return (
    <div>
      <Head>
        
        <title>One-Click-Pick</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header> <NavBar/> </header>


      <main className={styles.main}>
         <img id="forHer" src="https://jpl.a.bigcontent.io/v1/static/desktop-middle-banner-1704x740-fffb7009e9105d02cd60581b09c3c898" alt="" />
            <SlidesWomen/>
        <br/> <br/> <br/> <br/> <br/><br/>
            <ProSlides/>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          <span>Powered by</span>
          <span >
            <Image src="/One Click Pick png.png" alt="Vercel Logo" width={200} height={200} />
          </span>
      
        </a>
      </footer>

      </div>
  );
}